import picture from "@/public/mypicture.jpg";
export const metadata = {
  title: "Joan Portfolio",
  description: "Generated by Joan using Next.js",
};
// Typing children
type Props = { readonly children: React.ReactNode };
export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href={"/mypicture.jpg"} type="image/x-icon" />
      </head>
      <body>{children}</body>
    </html>
  );
}
